matrix:
  include:
    - language: csharp
      solution: TripCalculator.csproj
      mono: none
      sudo: required
      dist: xenial
      dotnet: 2.2
      before_script:
        - cd src
      script:
        - dotnet restore
        - dotnet test
    - language: node_js
      node_js:
        - "10.9"
      sudo: true
      before_script:
        - cd web/trip-calculator-frontend
        - echo 'n' | npm install -g @angular/cli
        - echo 'n' | npm install
      script:
        - ng lint
        - ng build